### ISSUE TITLE
railway up UX revamp tracking issue

### ISSUE THREAD

**Issue by GetPsyched** [railwayapp/cli#433]
As discussed in [this Discord thread](https://discord.com/channels/713503345364697088/1118206767214633010), with followup discussions here or [here](https://discord.com/channels/713503345364697088/1124096002341740686), this issue aims to refine the user experience of the `railway up` command when a service has not been linked. I will shoot a PR for this shortly.

## The problem

When using `up` in a project that's not linked to any project at all, it fails by redirecting the user to `link`. This is perfectly fine; however, the `link` command only does half the job for some reason, i.e., it only links the project and the environment but not any service (maybe there's some historical reason to support this but now seems redundant). So, once the user has completed `link`, they proceed back to `up` which then prompts the user for the service they want to push to. This is done each time the user runs `up`.

## The solution

The current solution is to link the service using the `service` command; however, conceptually, it makes more sense to also link the service using the `link` command and remove the code in `up` to prompt for the service.

## Breakdown

- [x] Add support to `link` to also link a service to a given directory.
- [ ] Drop support from `up` to prompt the user for a service.
- [ ] Sweep the `service` command once everything is fully tested and deployed.

**Comment by coffee-cup** [comment]
Thanks for the interest in improving the ergonomics of the railway ip command. However, I don’t think all of the proposed changes should be made. 

1. It’s a good idea to also link the service when railway link is run. +1
2. We should still support cases where there is no service linked. Currently, if there is no service and you run up then a service is created. If there is only a single service, we deploy to that. If there are multiple services and no service has been linked, we prompt (or you can specify with —service). I think we should keep this behaviour 
3. We should keep the service command as it is still useful even if the link command also links the service.

**Comment by GetPsyched** [comment]
> 2. We should still support cases where there is no service linked. Currently, if there is no service and you run up then a service is created. If there is only a single service, we deploy to that. If there are multiple services and no service has been linked, we prompt (or you can specify with —service). I think we should keep this behaviour

I disagree. If `link` supports linking the service along with other items, not having a service linked when running `up` wouldn't be possible, unless I'm missing something. If it isn't possible, then that's redundant code.

> 3. We should keep the service command as it is still useful even if the link command also links the service.

Fair enough.

**Comment by coffee-cup** [comment]
> What are the cases where there is no service linked at the time of running up if link has already linked the service as well?

If the service was created after `link` was run

**Comment by GetPsyched** [comment]
Hey, @coffee-cup, could you follow up on this?

**Comment by coffee-cup** [comment]
I don’t think we should force a service being created if none exist. If there are services already in the project, we can prompt to link one.

**Comment by GetPsyched** [comment]
> I don’t think we should force a service being created if none exist. If there are services already in the project, we can prompt to link one.

Why should we not? The `link` command is always run in the context of linking a local repository/directory to a project. Of course, a single directory will not correspond to an entire project but a single service of any given project. So, why should we not force this?

> We also have to handle when the service linked is invalid or deleted so we cannot assume that the project is always linked with a valid service.

Yes, that can be done whether or not we force linking a service; since the same can occur with an entire project being invalid/deleted when running `up`

**Comment by alexng353** [comment]
> * It’s a good idea to also link the service when railway link is run. +1

+1 I agree, its definitely possible for CLI to pull all the necessary data for service to be connected at the same time as link. If there is no service, CLI can throw the "no service" message with instructions on how to create one.

**Comment by coffee-cup** [comment]
> Why should we not? The link command is always run in the context of linking a local repository/directory to a project. Of course, a single directory will not correspond to an entire project but a single service of any given project. So, why should we not force this?

Because we also don't force a service being created when you create a new Railway project and it is valid to have a project in a zero service state.

**Comment by GetPsyched** [comment]
Fair point; however, it's important to note that `link` works with connecting a specific directory with a project and/or service. If the user already has a directory, then surely that's for a service.

When `link` is run, an entry to `projects` is added with the directory in which `link` was run in.
```json
  "projects": {
    "/home/getpsyched/git/project-hyperlink": {
      "projectPath": "/home/getpsyched/git/project-hyperlink",
      "name": "NKSSS",
      "project": "69531a0b-78b7-4a71-9df4-3a8db9703b69",
      "environment": "00a049de-6ff8-4329-ace9-27c152499094",
      "environmentName": "production",
      "service": null
    }
  },
```
If the user is running link, they already have a directory which they would want to push to an existing service or create one.

Yes, not having a service is a valid state for a project; but also why would a user want to link a directory to a project and not a service from a UX standpoint.

**Comment by coffee-cup** [comment]
> I can't see any scenario where this happens. Almost every CLI command requires a service.

Yes, but you are prompted for the service if you don't have one selected. For example, if you have a monorepo and use `railway up`, you are prompted to select the service you want to deploy. This is entirely valid and the user may not want to be forced into selecting a single service when the monorepo is actually connected to 2+ services on Railway and prompting is preferred.

**Comment by alexng353** [comment]
> This is entirely valid and the user may not want to be forced into selecting a single service when the monorepo is actually connected to 2+ services on Railway and prompting is preferred.

What about using monorepo detection and extra config fields to solve this issue? There are only so many monorepo solutions and I'm assuming that most people using railway use a singlerepo instead. Personally we use a monorepo but none of our environment variables are overlapping so slapping a `railway shell` on it is easiest.

**Comment by GetPsyched** [comment]
> This is entirely valid and the user may not want to be forced into selecting a single service when the monorepo is actually connected to 2+ services on Railway and prompting is preferred.

Fair. I forgot monorepos existed. But in that case, can't the user just run `link` for every sub-directory within the monorepo? If the issue is shared resources which can't be avoided, then there should be something done based on what @alexng353 mentioned above.

**Comment by alexng353** [comment]
> can't the user just run link for every sub-directory within the monorepo?

To be honest I think running link in every subdirectory kinda sucks and monorepo detection with a flag would be much better. I think it sucks because you then need to `cd` into every individual directory and the ergonomics are quite bad. As it is right now the chi's utilities aren't going to be very fun to implement monorepo support into, but it's definitely possible. We would have to really think about how we want it to be done in order to do it well.

**Comment by coffee-cup** [comment]
Linking every subdirectory does not work for Turbo or Nx monorepos since the root needs to be deployed for each sub-service. Only the build and start commands differ.

I think we are really overcomplicating this issue. Prompting for the service on `railway link` (or automatically selecting the first if there is only 1) will help the UX quite a bit.

**Comment by alexng353** [comment]
> Prompting for the service on railway link (or automatically selecting the first if there is only 1) will help the UX quite a bit.

Sounds like a pretty good solution, how about 'railway service default'

**Comment by GetPsyched** [comment]
Completed in #453

**Comment by Milo123459** [comment]
haha I didn't even notice

**Comment by GetPsyched** [comment]
It's all right. The changes I made on my fork were likely nowhere close to fixing this (the code was too confusing to understand easily)
